chck

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -35,13 +35,15 @@ jobs:
 
       - name: Deploy to Server
         env:
-          BRANCH_NAME: ${{ github.ref_name }}
-          DEST_FOLDER: "/www/simple-calculator.vkvaskov.com/${{ github.ref_name }}"
+          DEST_FOLDER: ${{ github.ref_name }}
+          BASE_DIR: "/var/www/ch05522979/www/simple-calculator.vkvaskov.com"
         run: |
           echo "Deploying to server..."
+
+          # Change directory to BASE_DIR
+          cd $BASE_DIR || { echo "Failed to change directory to $BASE_DIR." >&2; exit 1; }
           ls
-          cd /www/simple-calculator.vkvaskov.com || { echo "Failed to change directory." >&2; exit 1; }
-          ls
+
           # Create the destination folder if it doesn't exist
           mkdir -p $DEST_FOLDER || { echo "Failed to create destination folder." >&2; exit 1; }
 
